- backend/inventory/models.py
- backend/patient/models.py
Removed OrderBill Model
Removed OrderBill field in PatientAppointments
> removed Orderbill model

- backend/billing/admin.py
- backend/billing/apps.py
- backend/billing/models.py
- backend/billing/serializers.py
- backend/billing/tests.py
- backend/billing/urls.py
- backend/billing/views.py
- backend/makeeasyhmis/settings/base.py
- backend/makeeasyhmis/urls.py
> added billing module

- backend/patient/models.py
- backend/patient/serializers.py
Requires new db migrations for the patient and public appointment model
> Add email and phone number fields to public appointment and patient model

- backend/laboratory/serializers.py
- backend/patient/serializers.py
Added Item Name and Test Profile name to endpoints.
```
/patients/prescribed-drugs/by_patient_id/{patient_id}/
"item_name": "string",
/patients/appointments/by_patient_id/{patient_id}/
"item_name": "string",
/lab/lab-test-request-by-patient-id/{patient_id}/
"test_profile_name": "string",
"cost": "string",
```
> added item names

- front-end/src/components/dashboard/doctor-interface/doctor-patient-datagrid.js
- front-end/src/components/dashboard/inventory/PurchaseOrdersDatagrid.js
- front-end/src/components/dashboard/inventory/RequisitionDatagrid.js
- front-end/src/components/dashboard/inventory/index.js
- front-end/src/components/dashboard/nursing-interface/index.js
- front-end/src/components/dashboard/patient/patient-data-grid.js
- front-end/src/components/dashboard/pharmacy/index.js
- front-end/src/components/dashboard/reception-interface/booked-appointments-datagrid.js
- front-end/src/components/dashboard/reception-interface/patient-appointment-datagrid.js
this pr fixes pagination of tables
fixes #307 
[Screencast from 12-01-2024 12:08:22 WD.webm](https://github.com/PROTO-TYPE-SOLUTIONS/make-easy-hmis/assets/71401172/b1a2ac4d-b658-4f51-8bc3-bd9ea891059c)
> :lipstick: :art: fix pagination of tables

- front-end/package.json
- front-end/src/components/dashboard/inventory/AddInventory.js
- front-end/src/components/dashboard/inventory/create-purchase-order-dialog.js
- front-end/src/components/dashboard/inventory/create-requisition-dialog.js
- front-end/src/components/dashboard/patient/create-appointment-modal.js
- front-end/src/components/dashboard/reception-interface/assign-doctor-modal.js
- front-end/src/components/select/Searchable.js
this pr adds search functionality in select.
fixes #336
[Screencast from 13-01-2024 12:56:55 WB.webm](https://github.com/PROTO-TYPE-SOLUTIONS/make-easy-hmis/assets/71401172/9e83d817-8362-46ef-8553-1ee6745b4e95)
> :art: Appointment creation add items search

- front-end/src/assets/api-endpoints.js
- front-end/src/components/dashboard/inventory/AddProductPurchase.js
- front-end/src/components/dashboard/inventory/CreateRequisition.js
- front-end/src/components/dashboard/inventory/PurchaseOrdersDatagrid.js
- front-end/src/components/dashboard/inventory/RequisitionDatagrid.js
- front-end/src/pages/api/user/getAllUsers.js
- front-end/src/pages/api/user/getUserName.js
- front-end/src/redux/features/users/index.js
- front-end/src/redux/service/user/index.js
- front-end/src/redux/store.js
this pr uses id of logged in user as requested by while saving to db of purchase order and requisition
>  :art: save requested by with logged in user

- front-end/src/components/dashboard/billing/BillingNav.js
- front-end/src/components/dashboard/inventory/create-purchase-order-dialog.js
- front-end/src/components/dashboard/inventory/create-requisition-dialog.js
- front-end/src/components/layout/customized-header.js
- front-end/src/components/layout/sidebar/index.js
- front-end/src/pages/dashboard/ai-assistant/index.js
- front-end/src/pages/dashboard/billing/billed-datagrid.js
- front-end/src/pages/dashboard/billing/create-invoice/Appointments.js
- front-end/src/pages/dashboard/billing/create-invoice/ReviewInvoice.js
- front-end/src/pages/dashboard/billing/create-invoice/index.js
- front-end/src/pages/dashboard/billing/create-invoice/lab-test-requests.js
- front-end/src/pages/dashboard/billing/create-invoice/prescribed-drug.js
- front-end/src/pages/dashboard/billing/index.js
- front-end/src/pages/dashboard/doctor-interface/index.js
- front-end/src/pages/dashboard/laboratory/index.js
- front-end/src/pages/dashboard/laboratory/lab-requests.js
- front-end/src/pages/dashboard/laboratory/lab-results.js
- front-end/src/pages/dashboard/nursing-interface/index.js
- front-end/src/pages/dashboard/patients/index.js
- front-end/src/pages/dashboard/phamarcy/index.js
- front-end/src/pages/dashboard/reception-interface/index.js
- front-end/src/redux/features/billing/index.js
this pr displays the invoices and creation of invoice 
[Screencast from 17-01-2024  4:25:19 WB.webm](https://github.com/PROTO-TYPE-SOLUTIONS/make-easy-hmis/assets/71401172/35c4e074-b18a-4dd4-bd8e-976fb5b2299e)
> :sparkles: Billing module

- front-end/src/components/dashboard/inventory/CreateRequisition.js
- front-end/src/components/dashboard/pharmacy/PhamarcyNav.js
- front-end/src/pages/dashboard/billing/create-invoice/NewInvoice.js
- front-end/src/pages/dashboard/billing/create-invoice/index.js
- front-end/src/pages/dashboard/phamarcy/create-invoice/index.js
- front-end/src/pages/dashboard/phamarcy/create-requisition.js/index.js
- front-end/src/pages/dashboard/phamarcy/index.js
this pr adds invoice creation and requsition creation in pharmacy
> :sparkles: invoice and requisition creation inside pharmacy

- front-end/src/components/dashboard/doctor-interface/doctor-patient-datagrid.js
- front-end/src/components/dashboard/doctor-interface/prescriptionItemDialog.js
- front-end/src/components/select/Searchable.js
- front-end/src/pages/dashboard/billing/create-invoice/Appointments.js
- front-end/src/pages/dashboard/billing/create-invoice/ReviewInvoice.js
- front-end/src/pages/dashboard/doctor-interface/prescribe/[patient_id].js
- front-end/src/redux/features/patients/index.js
this pr adds the functionality to create a patient prescription together with its prescribed drugs.
[Screencast from 20-01-2024  2:34:40 WD.webm](https://github.com/PROTO-TYPE-SOLUTIONS/make-easy-hmis/assets/71401172/289a291b-f3e8-4b73-8943-cde9de3ba29b)
> :art: :sparkles: Prescription Creation

- front-end/src/assets/api-endpoints.js
- front-end/src/components/dashboard/doctor-interface/doctor-patient-datagrid.js
- front-end/src/components/dashboard/doctor-interface/lab-modal.js
- front-end/src/components/dashboard/inventory/AddInventory.js
- front-end/src/components/dashboard/inventory/incomingItems/IncomingItemsGrid.js
- front-end/src/components/dashboard/inventory/incomingItems/NewItems.js
- front-end/src/components/dashboard/inventory/nav.js
- front-end/src/pages/api/inventory/incomingItem.js
- front-end/src/pages/dashboard/billing/create-invoice/ReviewInvoice.js
- front-end/src/pages/dashboard/billing/create-invoice/lab-test-requests.js
- front-end/src/pages/dashboard/inventory/incoming-items/index.js
- front-end/src/pages/dashboard/inventory/incoming-items/new/index.js
- front-end/src/redux/features/inventory/index.js
- front-end/src/redux/service/inventory/index.js
this pr fixes the changes from endpoint requirement and passed required data and also incoming items module.
[Screencast from 24-01-2024 11:51:42 WD.webm](https://github.com/PROTO-TYPE-SOLUTIONS/make-easy-hmis/assets/71401172/bccd61d0-2c1f-4b0f-b42a-c630c9f5ec4b)
>  :alien: fixed what is sent to an endpoint and incoming items module

- front-end/src/assets/api-endpoints.js
- front-end/src/assets/menu.js
- front-end/src/components/account/AccountProfile.js
- front-end/src/components/account/ProfileEdit.js
- front-end/src/components/announcement/AnnouncementPosts.js
- front-end/src/components/announcement/NewPost.js
- front-end/src/components/layout/rightbar/top-section.js
- front-end/src/pages/account/announcements/index.js
- front-end/src/pages/account/profile/index.js
- front-end/src/pages/api/announcement/announcements.js
- front-end/src/pages/api/announcement/channels.js
- front-end/src/redux/features/announcements/index.js
- front-end/src/redux/service/announcements/index.js
- front-end/src/redux/store.js
this pr allows users post and view top 5 latest announcements
[Screencast from 26-01-2024  5:39:35 WB.webm](https://github.com/PROTO-TYPE-SOLUTIONS/make-easy-hmis/assets/71401172/cba1cd39-d943-42a1-abc6-aec72fde6a7f)
> added announcements module

- front-end/src/components/account/AccountProfile.js
- front-end/src/components/announcement/AnnouncementPosts.js
- front-end/src/components/announcement/NewPost.js
- front-end/src/pages/account/announcements/index.js
- front-end/src/pages/index.js
> :lipstick: Improved announcements UI and :art: Redirect to dashboard if user is present

- front-end/src/components/announcement/AnnouncementPosts.js
- front-end/src/components/announcement/ChannelCards.js
- front-end/src/components/dashboard/pharmacy/index.js
- front-end/src/pages/account/announcements/index.js
- front-end/src/pages/dashboard/announcements/channel/[channel_name].js
- front-end/src/pages/dashboard/announcements/index.js
[Screencast from 29-01-2024  3:35:31 WB.webm](https://github.com/PROTO-TYPE-SOLUTIONS/make-easy-hmis/assets/71401172/bf0db7ef-bee3-481e-8fba-3304b4f4d41f)
> :art: announcement by page

- front-end/src/assets/api-endpoints.js
- front-end/src/components/dashboard/laboratory/LabNav.js
- front-end/src/components/dashboard/laboratory/add-result/AddTestResults.js
- front-end/src/components/dashboard/laboratory/add-result/LabItemModal.js
- front-end/src/components/dashboard/laboratory/lab-results-datagrid.js
- front-end/src/pages/api/laboratory/get-lab-results.js
- front-end/src/pages/api/laboratory/get-lab-test-panels.js
- front-end/src/pages/api/laboratory/get-lab-test-result-item.js
- front-end/src/pages/dashboard/laboratory/add-results/index.js
- front-end/src/redux/features/laboratory/index.js
- front-end/src/redux/service/laboratory/index.js
this pr adds lab results functionality to add test results and its items
[Screencast from 30-01-2024  7:22:30 WB.webm](https://github.com/PROTO-TYPE-SOLUTIONS/make-easy-hmis/assets/71401172/6a77e25d-f24a-4cd0-9ec9-80d47f000b54)
> :art: :sparkles: add test results andi its items

- front-end/src/components/dashboard/inventory/PurchaseOrdersDatagrid.js
- front-end/src/components/dashboard/inventory/RequisitionDatagrid.js
- front-end/src/components/dashboard/inventory/incomingItems/IncomingItemsGrid.js
- front-end/src/components/dashboard/inventory/index.js
- front-end/src/components/dashboard/laboratory/lab-results-datagrid.js
- front-end/src/components/dashboard/pharmacy/index.js
> :art: added print action as a menu item

- front-end/src/components/dashboard/laboratory/LabNav.js
- front-end/src/components/dashboard/laboratory/convert-req-modal.js
- front-end/src/components/dashboard/laboratory/public-lab-requests-datagrid.js
- front-end/src/pages/api/laboratory/public-lab-request.js
- front-end/src/pages/book-appointment/index.js
- front-end/src/pages/book-appointment/lab-service.js
- front-end/src/pages/dashboard/laboratory/public-lab-requests.js
- front-end/src/redux/features/laboratory/index.js
- front-end/src/redux/service/laboratory/index.js
[Screencast from 03-02-2024  4:03:05 WB.webm](https://github.com/PROTO-TYPE-SOLUTIONS/make-easy-hmis/assets/71401172/691166c9-7bc7-488b-8324-d70a5e82cc04)
> :construction: public lab requests functionality

- front-end/src/assets/api-endpoints.js
- front-end/src/components/layout/profile-layout.js
- front-end/src/components/patient-profile/lab/AddLabReq.js
- front-end/src/components/patient-profile/lab/LabRequestsGrid.js
- front-end/src/components/patient-profile/prescriptions/MyPrescriptions.js
- front-end/src/components/patient-profile/prescriptions/PatientPrescriptionRequest.js
- front-end/src/pages/api/patient-profile/patientlabtestrequest.js
- front-end/src/pages/api/patient-profile/patientprescriptionrequest.js
- front-end/src/pages/patient-overview/lab-requests/index.js
- front-end/src/pages/patient-overview/profile/index.js
- front-end/src/redux/service/patientUser/index.js
this pr adds functionality to request lab test request and prescription as a patient
> :sparkles: added patient lab test request and patient prescription request functionality

- front-end/src/components/layout/rightbar/top-section.js
- front-end/src/components/notifications/Notifications.js
[Screencast from 02-03-2024  8:48:38 WB.webm](https://github.com/PROTO-TYPE-SOLUTIONS/make-easy-hmis/assets/71401172/2bdf4bbb-606b-4d62-bcbe-8f5797ab62e6)
> :construction: notifications

- backend/inventory/models.py
- backend/inventory/serializers.py
- backend/inventory/signals.py
- backend/inventory/tests/test_inventory_signals.py
- backend/inventory/tests/test_supplier_invoice.py
- backend/inventory/views.py
Added functionality to automatically update Supplier Invoice amounts whenever related Incoming Items are created, modified, or deleted.
Created a signal that triggers on:
- Creating a new Incoming Item
- Updating an existing Incoming Item
- Deleting an Incoming Item
> Supplier amount calculation

- front-end/src/components/dashboard/laboratory/TestPanelsItem.js
- front-end/src/components/layout/sidebar/index.js
- Added an action button to send the test request to the selected equipment
- Fixed hospital logo display
> Added an action button to send the test request to the selected equipment

- backend/inventory/models.py
- backend/inventory/serializers.py
- backend/inventory/tests/test_department_transfers.py
Implemented a  department inventory transfer system that manages inventory movements between departments following FIFO (First-In-First-Out) principles and maintains accurate stock tracking across multiple lots.
1. **FIFO-based Transfers**
- Implements FIFO logic to ensure oldest inventory batches are transferred first
- Automatically handles transfers across multiple lots when a single lot has insufficient quantity
2. ** Lot Management**
- Maintains lot numbers and expiry dates during transfers
- Supports transferring to existing lots in destination departments
- Updates quantities  when adding to existing department lots
> feat: Add departmental transfers from main inventory

- backend/billing/admin.py
- backend/billing/signals.py
- backend/requirements_bk.txt
Added signal to update Invoice.cash_paid on InvoicePayment save
> update cash_paid on InvoicePayments save

- backend/conftest.py
- backend/inventory/tests/test_requisition_process.py
- backend/laboratory/models.py
- backend/laboratory/serializers.py
- backend/laboratory/tests/test_patient_sample.py
The code format is DDLRXXXXX/YYYY, where XXXXX is a 5-digit sequential number and YYYY is the current year. The sequence number resets to 00001 at the beginning of each year.
> Format Sample ID

- backend/billing/models.py
- backend/billing/serializers.py
The format is DDLIXXXXX/YYYY, where XXXXX is a 5-digit sequential number and YYYY is the current year. The sequence resets to 00001 at the beginning of each year.
> Format Invoice ID

- front-end/src/assets/menu.js
- front-end/src/components/dashboard/admit/AdmitNav.js
- front-end/src/components/dashboard/admit/admit-patient-datagrid.js
- front-end/src/components/dashboard/admit/wards.js
- front-end/src/components/dashboard/doctor-interface/doctor-patient-datagrid.js
- front-end/src/pages/dashboard/admit/index.js
- front-end/src/pages/dashboard/admit/wards.js
Inpatient added to the dashboard
the patients and wards data grid too
> "In-patemt ui "

- front-end/src/assets/hoc/not-authorised.js
- front-end/src/assets/hoc/patient-confirmed.js
- front-end/src/components/dashboard/admin-interface/edit-patient-details-modal.js
- front-end/src/components/layout/rightbar/booked-sessions.js
- front-end/src/pages/dashboard/reception-interface/booked-appointments.js
- front-end/src/pages/index.js
- Check if token is available first before attempting to fetch
- If a user tries accesing a page they are not authorised, they are taken to not authorised page where they can click the button which shows a default page for the user i.e a doctor can go back to doctors page, nurse back to nurse page. this is dependent on the users ro;e
closes #754
> Fix Issue with token invalidation after refresh 754

- backend/billing/templates/invoice.html
- backend/billing/views.py
- backend/inpatient/filters.py
- backend/inpatient/serializers.py
- backend/inpatient/views.py
I have added filters for admitted and discharged patients like so:
Discharged:
Admitted:
> Discharged and Admitted filter

- backend/billing/templates/invoice.html
- backend/billing/views.py
> Wrong Invoice amounts

- backend/inventory/models.py
- backend/inventory/signals.py
- backend/inventory/tasks.py
> added default insurance sale prie logic on inventory create
